#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[toolchain]
channel = "nightly-2024-09-01"
components = [ "rustfmt", "rust-src" ]
targets = ["aarch64-unknown-none"]
