#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[workspace]

resolver = "2"

members = [
    "hello-world",
    "kernel-objects",
    "address-space",
    "serial-device",
    "spawn-thread",
    "spawn-task",
    "spawn-task/child",
]
